/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */

export type CommentsControllerPaginateCommentsParams = {
  page?: number;
  where__id__more_than?: number;
  where__id__less_than?: number;
  order__createdAt?: string;
  take?: number;
};
