/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */

export interface CreateCommentDto {
  /** 댓글 본문 */
  comments: string;
}
