/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */

/**
 * 이미지 타입
 */
export type ImageModelType = (typeof ImageModelType)[keyof typeof ImageModelType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageModelType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
