/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import type { UsersModel } from './usersModel';
import type { ImageModel } from './imageModel';

export interface PostsModel {
  /** PK ID */
  id: number;
  /** 생성일시 */
  createdAt: string;
  /** 수정일시 */
  updatedAt: string;
  author: UsersModel;
  title: string;
  subTitle?: string;
  content: string;
  likeCount: number;
  commentCount: number;
  comments: string[];
  images: ImageModel[];
}
