/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


export const postsControllerGetPostsQueryParams = zod.object({
  "page": zod.number().optional(),
  "where__id__more_than": zod.number().optional(),
  "where__id__less_than": zod.number().optional(),
  "order__createdAt": zod.string().optional(),
  "take": zod.number().optional(),
  "where__likeCount__more_than": zod.number().optional(),
  "where__title__i_like": zod.string().optional()
})

export const postsControllerGetPostsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "author": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "nickname": zod.string().describe('닉네임 (2~20자)'),
  "email": zod.string().describe('이메일 주소'),
  "nicknameAndEmail": zod.object({

}).describe('닉네임과 이메일을 합친 가상 필드 (출력용)'),
  "password": zod.string().describe('비밀번호 (8~20자)'),
  "role": zod.enum(['user', 'admin']).describe('사용자 권한'),
  "posts": zod.array(zod.any()).describe('작성한 게시글 목록'),
  "chats": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('참여 중인 채팅방 목록'),
  "messages": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('작성한 메시지 목록'),
  "image": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "order": zod.number().optional().describe('이미지 순서 (default: 0)'),
  "type": zod.literal(0).or(zod.literal(1)).describe('이미지 타입'),
  "path": zod.string().describe('이미지 경로 (POST_IMAGE 타입이면 자동으로 경로 Prefix 추가)'),
  "post": zod.any().optional().describe('이미지가 소속된 게시물'),
  "user": zod.any().optional().describe('이미지가 소속된 프로필')
}).describe('프로필 사진'),
  "postComments": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
}).describe('작성한 댓글')
}),
  "title": zod.string(),
  "subTitle": zod.string().optional(),
  "content": zod.string(),
  "likeCount": zod.number(),
  "commentCount": zod.number(),
  "comments": zod.array(zod.string()),
  "images": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "order": zod.number().optional().describe('이미지 순서 (default: 0)'),
  "type": zod.literal(0).or(zod.literal(1)).describe('이미지 타입'),
  "path": zod.string().describe('이미지 경로 (POST_IMAGE 타입이면 자동으로 경로 Prefix 추가)'),
  "post": zod.any().optional().describe('이미지가 소속된 게시물'),
  "user": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "nickname": zod.string().describe('닉네임 (2~20자)'),
  "email": zod.string().describe('이메일 주소'),
  "nicknameAndEmail": zod.object({

}).describe('닉네임과 이메일을 합친 가상 필드 (출력용)'),
  "password": zod.string().describe('비밀번호 (8~20자)'),
  "role": zod.enum(['user', 'admin']).describe('사용자 권한'),
  "posts": zod.array(zod.any()).describe('작성한 게시글 목록'),
  "chats": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('참여 중인 채팅방 목록'),
  "messages": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('작성한 메시지 목록'),
  "image": zod.any().describe('프로필 사진'),
  "postComments": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
}).describe('작성한 댓글')
}).optional().describe('이미지가 소속된 프로필')
}))
})),
  "total": zod.number().optional(),
  "next": zod.string().nullish(),
  "count": zod.number().nullish(),
  "cursor": zod.object({
  "after": zod.number().nullish()
}).nullish()
})

export const postsControllerPostPostsBody = zod.object({
  "images": zod.array(zod.string()),
  "title": zod.string(),
  "content": zod.string(),
  "subTitle": zod.string().optional()
})

export const postsControllerGetPostParams = zod.object({
  "id": zod.number()
})

export const postsControllerGetPostResponse = zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "author": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "nickname": zod.string().describe('닉네임 (2~20자)'),
  "email": zod.string().describe('이메일 주소'),
  "nicknameAndEmail": zod.object({

}).describe('닉네임과 이메일을 합친 가상 필드 (출력용)'),
  "password": zod.string().describe('비밀번호 (8~20자)'),
  "role": zod.enum(['user', 'admin']).describe('사용자 권한'),
  "posts": zod.array(zod.any()).describe('작성한 게시글 목록'),
  "chats": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('참여 중인 채팅방 목록'),
  "messages": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('작성한 메시지 목록'),
  "image": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "order": zod.number().optional().describe('이미지 순서 (default: 0)'),
  "type": zod.literal(0).or(zod.literal(1)).describe('이미지 타입'),
  "path": zod.string().describe('이미지 경로 (POST_IMAGE 타입이면 자동으로 경로 Prefix 추가)'),
  "post": zod.any().optional().describe('이미지가 소속된 게시물'),
  "user": zod.any().optional().describe('이미지가 소속된 프로필')
}).describe('프로필 사진'),
  "postComments": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
}).describe('작성한 댓글')
}),
  "title": zod.string(),
  "subTitle": zod.string().optional(),
  "content": zod.string(),
  "likeCount": zod.number(),
  "commentCount": zod.number(),
  "comments": zod.array(zod.string()),
  "images": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "order": zod.number().optional().describe('이미지 순서 (default: 0)'),
  "type": zod.literal(0).or(zod.literal(1)).describe('이미지 타입'),
  "path": zod.string().describe('이미지 경로 (POST_IMAGE 타입이면 자동으로 경로 Prefix 추가)'),
  "post": zod.any().optional().describe('이미지가 소속된 게시물'),
  "user": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시'),
  "nickname": zod.string().describe('닉네임 (2~20자)'),
  "email": zod.string().describe('이메일 주소'),
  "nicknameAndEmail": zod.object({

}).describe('닉네임과 이메일을 합친 가상 필드 (출력용)'),
  "password": zod.string().describe('비밀번호 (8~20자)'),
  "role": zod.enum(['user', 'admin']).describe('사용자 권한'),
  "posts": zod.array(zod.any()).describe('작성한 게시글 목록'),
  "chats": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('참여 중인 채팅방 목록'),
  "messages": zod.array(zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
})).describe('작성한 메시지 목록'),
  "image": zod.any().describe('프로필 사진'),
  "postComments": zod.object({
  "id": zod.number().describe('PK ID'),
  "createdAt": zod.string().datetime({}).describe('생성일시'),
  "updatedAt": zod.string().datetime({}).describe('수정일시')
}).describe('작성한 댓글')
}).optional().describe('이미지가 소속된 프로필')
}))
})

export const postsControllerPatchPostParams = zod.object({
  "id": zod.number()
})

export const postsControllerPatchPostBody = zod.object({

})

export const postsControllerDeletePostParams = zod.object({
  "id": zod.number()
})

