/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


export const chatMessagesControllerPaginateMessagesParams = zod.object({
  "cid": zod.number()
})

export const chatMessagesControllerPaginateMessagesQueryParams = zod.object({
  "page": zod.number().optional(),
  "where__id__more_than": zod.number().optional(),
  "where__id__less_than": zod.number().optional(),
  "order__createdAt": zod.string().optional(),
  "take": zod.number().optional()
})

export const chatMessagesControllerPostMessageParams = zod.object({
  "cid": zod.number()
})

export const chatMessagesControllerPostMessageBody = zod.object({
  "chatId": zod.number().describe('채팅방 ID'),
  "authorId": zod.number().describe('작성자 ID')
})

