/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * Blob 이미지를 업로드합니다.
 * @summary 이미지 업로드
 */
export const commonControllerPostImageBody = zod.object({
  "image": zod.instanceof(File).optional()
})

export const commonControllerPostImageResponse = zod.object({
  "fileName": zod.string().optional()
})

