/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


export const usersControllerGetUserParams = zod.object({
  "id": zod.number()
})

export const usersControllerUpdateUserParams = zod.object({
  "id": zod.number()
})

export const usersControllerUpdateUserBody = zod.object({

})

