/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import type { CommentDto } from './commentDto';
import type { CommentsPaginateResponseDtoCursor } from './commentsPaginateResponseDtoCursor';

export interface CommentsPaginateResponseDto {
  data: CommentDto[];
  total?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  count?: number | null;
  /** @nullable */
  cursor?: CommentsPaginateResponseDtoCursor;
}
