/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type CommentAuthorDtoImage = { [key: string]: unknown } | null;
