/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import type { CommentAuthorDtoImage } from './commentAuthorDtoImage';

export interface CommentAuthorDto {
  id: number;
  nickname: string;
  /** @nullable */
  image: CommentAuthorDtoImage;
}
