/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import type { CommentAuthorDto } from './commentAuthorDto';

export interface CommentDto {
  id: number;
  comments: string;
  likeCount: number;
  author: CommentAuthorDto;
  createdAt: string;
  updatedAt: string;
}
