/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import type { ImageModelType } from './imageModelType';
import type { PostsModel } from './postsModel';
import type { UsersModel } from './usersModel';

export interface ImageModel {
  /** PK ID */
  id: number;
  /** 생성일시 */
  createdAt: string;
  /** 수정일시 */
  updatedAt: string;
  /** 이미지 순서 (default: 0) */
  order?: number;
  /** 이미지 타입 */
  type: ImageModelType;
  /** 이미지 경로 (POST_IMAGE 타입이면 자동으로 경로 Prefix 추가) */
  path: string;
  /** 이미지가 소속된 게시물 */
  post?: PostsModel;
  /** 이미지가 소속된 프로필 */
  user?: UsersModel;
}
