/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */

/**
 * 사용자 권한
 */
export type UsersModelRole = typeof UsersModelRole[keyof typeof UsersModelRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersModelRole = {
  user: 'user',
  admin: 'admin',
} as const;
