/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */

/**
 * 닉네임과 이메일을 합친 가상 필드 (출력용)
 */
export type UsersModelNicknameAndEmail = { [key: string]: unknown };
