/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { axiosInstance } from '../../../orval.axios';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const commonControllerPostImage = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/common/image`, method: 'POST', signal
    },
      );
    }
  


export const getCommonControllerPostImageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonControllerPostImage>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof commonControllerPostImage>>, TError,void, TContext> => {

const mutationKey = ['commonControllerPostImage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonControllerPostImage>>, void> = () => {
          

          return  commonControllerPostImage()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CommonControllerPostImageMutationResult = NonNullable<Awaited<ReturnType<typeof commonControllerPostImage>>>
    
    export type CommonControllerPostImageMutationError = unknown

    export const useCommonControllerPostImage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonControllerPostImage>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof commonControllerPostImage>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCommonControllerPostImageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    