/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Sabujak
 * 사부작 API Description
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


export const commentsControllerPaginateCommentsParams = zod.object({
  "postId": zod.number()
})

export const commentsControllerPaginateCommentsQueryParams = zod.object({
  "page": zod.number().optional(),
  "where__id__more_than": zod.number().optional(),
  "where__id__less_than": zod.number().optional(),
  "order__createdAt": zod.string().optional(),
  "take": zod.number().optional()
})

export const commentsControllerPostCommentParams = zod.object({
  "postId": zod.number()
})

export const commentsControllerPostCommentBody = zod.object({

})

export const commentsControllerDeleteCommentParams = zod.object({
  "postId": zod.number()
})

